const seed = [{id:"1", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/altima-white-exterior-outdoors.jpg.ximg.l_full_m.smart.jpg", car_id: "1", car_name: "Nissan Altima", car_color: "White", media_type: "image"},
  {id:"2", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/altima-white-exterior-outdoors-rear.jpg.ximg.l_full_m.smart.jpg", car_id: "1", car_name: "Nissan Altima", car_color: "White", media_type: "image"},
  {id:"3", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/hqdefault.jpg", car_id: "1", car_name: "Nissan Altima", car_color: "White", media_type: "image"},
  {id:"4", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/71634477.jpg", car_id: "1", car_name: "Nissan Altima", car_color: "White", media_type: "image"},
  {id:"5", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/2018nic040001_640_12.jpg", car_id: "1", car_name: "Nissan Altima", car_color: "White", media_type: "image"},
  {id:"6", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/maxresdefault.jpg", car_id: "2", car_name: "Ferrari Enzo", car_color: "Grey", media_type: "image"},
  {id:"7", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/2006-ferrari-enzo.webp", car_id: "2", car_name: "Ferrari Enzo", car_color: "Grey", media_type: "image"},
  {id:"8", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/ca0816-261991_12%402x.jpg", car_id: "2", car_name: "Ferrari Enzo", car_color: "Grey", media_type: "image"},
  {id:"9", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/2018_mercedes_benz_e_class_angularfront.jpg", car_id: "2", car_name: "Ferrari Enzo", car_color: "Grey", media_type: "image"},
  {id:"10", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/2016-Ford-Mustang-GT-burnout-red-tire-smoke.jpg", car_id: "3", car_name: "Ford Mustang GT", car_color: "Red", media_type: "image"},
  {id:"11", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/2019-mclaren-senna-hypercar-official-photos-and-info-news-car-and-driver-photo-698055-s-original.jpg", car_id: "3", car_name: "Ford Mustang GT", car_color: "Red", media_type: "image"},
  {id:"12", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/BMW-TA.jpg", car_id: "3", car_name: "Ford Mustang GT", car_color: "Red", media_type: "image"},
  {id:"13", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/download.jpeg", car_id: "3", car_name: "Ford Mustang GT", car_color: "Red", media_type: "image"},
  {id:"14", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/USC70JES052A021001.png", car_id: "3", car_name: "Ford Mustang GT", car_color: "Red", media_type: "image"},
  {id:"15", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/650.jpeg", car_id: "4", car_name: "Jeep", car_color: "White", media_type: "image"},
  {id:"16", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/images.jpeg", car_id: "4", car_name: "Jeep", car_color: "White", media_type: "image"},
  {id:"17", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/images+(1).jpeg", car_id: "4", car_name: "Jeep", car_color: "White", media_type: "image"},
  {id:"18", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/images+(2).jpeg", car_id: "4", car_name: "Jeep", car_color: "White", media_type: "image"},
  {id:"19", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/4722_38831281235_d4f294af57_320_240_nofilter.jpg", car_id: "4", car_name: "Jeep", car_color: "White", media_type: "image"},
  {id:"20", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/943_41024521054_8155e05479_320_240_nofilter.jpg", car_id: "4", car_name: "Jeep", car_color: "White", media_type: "image"},
  {id:"21", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/tesla-roadster-clay-model-design-5-e1512415837750.jpg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"22", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/Elon_Musk's_Tesla_Roadster.jpg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"23", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/tesla-roadster-2020-3d-model-max-obj-3ds-fbx-c4d-lwo-lw-lws.jpg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"24", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/Tesla-Model-3-wallpaper-red.jpg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"25", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/download+(1).jpeg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"26", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/images+(5).jpeg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"27", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/tesla-semi_46.jpg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"28", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/images+(4).jpeg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"29", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/5c665f17ef_1024.jpg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"30", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/Screen_Shot_2017-11-27_at_2.55.49_PM_grande.png", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"31", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/images+(3).jpeg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"32", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/Roadster_Front_58.0.jpg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"33", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/red-tesla-roadster-palo-alto-hq.jpg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"34", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/thumb_01.jpg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"35", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/Roadster_Front_58.0+(1).jpg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"36", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/8616.jpg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"37", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/tesla-roadster-red-multi-coat.jpg", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "image"},
  {id:"38", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/Tesla+next+gen+Roadster+red+exterior+shots+++launching.mp4", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "video"},
  {id:"39", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/Tesla+Roadster+(2020)+The+Quickest+Car+in+the+World.mp4", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "video"},
  {id:"40", media_url: "https://s3-us-west-1.amazonaws.com/carpics25/2020+Tesla+Roadster+Vs+2018+Bugatti+Chiron+-+Top+Speed!!.mp4", car_id: "5", car_name: "Tesla Roadster", car_color: "Red", media_type: "video"}]

module.exports = {
  seed: seed
}